### ISSUE TITLE
ChanduPriya_LogMessage_Oct 2023

### ISSUE THREAD

**Issue by ChandupriyaY** [vajrang-b/RPA-Developer-in-30-Days#1028]
[ChanduPriya_LogMessage.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/12819508/ChanduPriya_LogMessage.1.0.1.zip)

**Comment by Narendervajrangorg** [comment]
Hi @ChandupriyaY I have deployed your code and process executed successfully.
