### ISSUE TITLE
Manisha's_LogMessage

### ISSUE THREAD

**Issue by manishakintali** [vajrang-b/RPA-Developer-in-30-Days#1030]
LogMessage

**Comment by Swasa161211** [comment]
@manishakintali 

Please attach your package in the comment section.

**Comment by manishakintali** [comment]
[LogMessage_Manishaa.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/12832849/LogMessage_Manishaa.1.0.1.zip)

**Comment by swathinelakurthi** [comment]
@manishakintali 

Your code has been successfully deployed and executed in prod environment.
