### ISSUE TITLE
Kanna_LogMessege

### ISSUE THREAD

**Issue by Elshaddai0908** [vajrang-b/RPA-Developer-in-30-Days#1039]
[Kanna_LogMessage.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/12826847/Kanna_LogMessage.1.0.1.zip)

**Comment by Elshaddai0908** [comment]
Please check out the code. @narendar.

Thanks

**Comment by Narendervajrangorg** [comment]
Hi @Elshaddai0908 Your code has deployed successfully.
