### ISSUE TITLE
Yuvaraj_Log_Time

### ISSUE THREAD

**Issue by YuvarajKalaimani** [vajrang-b/RPA-Developer-in-30-Days#1040]
Please publish my package and run it.
[Yuvaraj_Log.Time.1.0.2.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/12831220/Yuvaraj_Log.Time.1.0.2.zip)

**Comment by swathinelakurthi** [comment]
@YuvarajKalaimani 
Please modify the package name and publish it and create an issue again.
