### ISSUE TITLE
Sandesh_Logmessage2

### ISSUE THREAD

**Issue by Sandesh-77** [vajrang-b/RPA-Developer-in-30-Days#1048]
[Sandesh_Logmessage2.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/12844365/Sandesh_Logmessage2.1.0.1.zip)

**Comment by swathinelakurthi** [comment]
@Sandesh-77 
Your code has been successfully deployed and executed in prod environment.
