### ISSUE TITLE
Sruthi Log message Deployment

### ISSUE THREAD

**Issue by sharidas2210** [vajrang-b/RPA-Developer-in-30-Days#1152]
[Test.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/13269177/Test.1.0.1.zip)

Deployed into Prod environment.

**Comment by suvedharan** [comment]
@sharidas2210 Please update the package with the proper naming conversation

**Comment by sharidas2210** [comment]
Changes made
[DateUser_Sruthi.1.0.2.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/13269672/DateUser_Sruthi.1.0.2.zip)
