### ISSUE TITLE
Test_Sample_Praveenraja

### ISSUE THREAD

**Issue by PRAVEENRAJA1699** [vajrang-b/RPA-Developer-in-30-Days#1156]
[Test_Sample_Praveenraja.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/13270062/Test_Sample_Praveenraja.1.0.1.zip)

**Comment by suvedharan** [comment]
@PRAVEENRAJA1699  Executed Successful
