### ISSUE TITLE
Screenshot name is in-correct format. 

### ISSUE THREAD

**Issue by sundaravalli2019** [vajrang-b/RPA-Developer-in-30-Days#125]
External user name is not updated in the screenshot file name.

**Comment by vajrang-b** [comment]
@ganesh-soley  Could you please check with this issue

**Comment by ganesh-soley** [comment]
> External user name is not updated in the screenshot file name.

@sundaravalli2019  file name format is External User_today's date time

**Comment by vajrang-b** [comment]
#128  issue resolved
