### ISSUE TITLE
Enhancement for log triveni

### ISSUE THREAD

**Issue by vajrang-b** [vajrang-b/RPA-Developer-in-30-Days#1423]
Update host name instead of static name @lakshmitrivenisareddy

**Comment by lakshmitrivenisareddy** [comment]
Enhancement completed ready for Deployment
[Triveni.log.message.week1.1.0.2.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/13844291/Triveni.log.message.week1.1.0.2.zip)
