### ISSUE TITLE
Data Base Project

### ISSUE THREAD

**Issue by Pavankumar1411** [vajrang-b/RPA-Developer-in-30-Days#1430]
Hi @Vineeth039 

Can you please look into the attached projects and start your work.

Regards,
Pavankumar.
[robot-logs-2023-12-13-06-22-30-953-30801.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/13848674/robot-logs-2023-12-13-06-22-30-953-30801.zip)

**Comment by Vineeth039** [comment]
Hi Pawan 

@Pavankumar1411 I am working on it and will let u know if am facing any issuue

Thanks 
Vineeth

**Comment by Vineeth039** [comment]
@Pavankumar1411 

adding for reference

**Comment by Pavankumar1411** [comment]
@Vineeth039 

Thanks for your efforts.

**Comment by Vineeth039** [comment]
@Pavankumar1411  Isuue rsolved clsoing the PR
