### ISSUE TITLE
Gowri wee1 background package QA deployment ready

### ISSUE THREAD

**Issue by gowribolem** [vajrang-b/RPA-Developer-in-30-Days#1436]
[Gowri.log.message.week1.1.0.1.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/13859102/Gowri.log.message.week1.1.0.1.zip)

**Comment by yeafi-al** [comment]
Process Execution Completed, I downloaded Gowri's zip file and deployed it in the orchestrator. My issue number is #1446
