### ISSUE TITLE
Shankar Upper case Generator

### ISSUE THREAD

**Issue by shankar6777** [vajrang-b/RPA-Developer-in-30-Days#1697]
Read input from excel
Generate uppercase words
Create report
Send report over email

- [x]  PDD
- [ ]  SDD
- [ ]  Coding
- [ ]  Testing
- [ ]  Deployment
[Upper case generator.docx](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/14999788/Upper.case.generator.docx)

**Comment by shankar6777** [comment]
@vajrang can you add input file

**Comment by vajrang-b** [comment]
> [@vajrang](https://github.com/vajrang) can you add input file

you can keep following words in excel and continue development

1@eerrr
avia
asdrr
Hiid8dd

**Comment by shankar6777** [comment]
@vajrang-b can you provide the website from whic i need to extract data

**Comment by vajrang-b** [comment]
also 

> [@vajrang-b](https://github.com/vajrang-b) can you provide the website from whic i need to extract data

please use this https://www.vajrang.org/trainings/challenges/uppercase
