### ISSUE TITLE
write extracted report to excel

### ISSUE THREAD

**Issue by vajrang-b** [vajrang-b/RPA-Developer-in-30-Days#194]
- [ ] two tables must be extracted
- [ ] Data should be seperate for each curency
- [ ] All data must be added to a single excel file with current date (ddmmyyyy)

**Comment by sgsiddalinga** [comment]
I am adding my name

**Comment by pallavi1208** [comment]
i am assign it to me

**Comment by Aakashhargude007** [comment]
Assign me

**Comment by sathish4512** [comment]
assign to me

**Comment by 8050164107** [comment]
assign to me
