### ISSUE TITLE
Projects_NewLogMsg_Jeevan

### ISSUE THREAD

**Issue by JeevanVarmaS** [vajrang-b/RPA-Developer-in-30-Days#1950]
LogMessage

**Comment by JeevanVarmaS** [comment]
Version - 2024
Completed the Task

**Comment by vajrang-b** [comment]
![Image](https://github.com/vajrang-b/UiPathIn30Days/assets/5066917/7ee3dcb1-6815-49a5-809c-b02fd7124770)

**Comment by JeevanVarmaS** [comment]
![Image](https://github.com/vajrang-b/UiPathIn30Days/assets/166020855/c7d62a9a-ab2b-4a54-8434-958ebe06606c)
