### ISSUE TITLE
clear errors in process flow of FDA REF

### ISSUE THREAD

**Issue by vajrang-b** [vajrang-b/RPA-Developer-in-30-Days#233]
![image](https://user-images.githubusercontent.com/5066917/143171314-30ba0479-1e4e-45b3-8bf2-3cec7e3fb881.png)

**Comment by shivamsr7** [comment]
I will work on this and send a pull request once cleared the errors.

**Comment by shivamsr7** [comment]
Bug #233: 
1)Data Table variable with name 'dt_Ongoing' was not existing in the code hence created a variable with this name.
2) Variable names City, Address_1, status, County was not existing in the sequence hence added these variables in the code.
