### ISSUE TITLE
Friut_Check: Create a flowchart for complete process.

### ISSUE THREAD

**Issue by MahammadGouse154** [vajrang-b/RPA-Developer-in-30-Days#260]

**Comment by MahammadGouse154** [comment]
We have created a flowchart based on BRD document steps and process flow.

Kindly share your valuable inputs.


![Fruits project Flowchart - By Mahammad](https://user-images.githubusercontent.com/95667250/147365492-01b75850-cae0-48f4-ad86-35195211379e.jpg)

**Comment by Yesuraju1234** [comment]
Ok Thanks you for sharing Modh

**Comment by saritharac** [comment]
Thank you

**Comment by vajrang-b** [comment]
@MahammadGouse154  Need to change this flow using swimlanes check that out

**Comment by vajrang-b** [comment]
Convert flow chart to swimlanes

**Comment by vajrang-b** [comment]
![Fruits project Flowchart diagram swimlanes](https://user-images.githubusercontent.com/5066917/147397732-78ed2289-4b7c-449d-a3f3-edde2530b500.jpg)
