### ISSUE TITLE
Project Structure Creation for Fruit API

### ISSUE THREAD

**Issue by shaktisingh22** [vajrang-b/RPA-Developer-in-30-Days#279]
@thrishula

**Comment by shaktisingh22** [comment]
@MahammadGouse154

**Comment by vajrang-b** [comment]
@Yesuraju1234

**Comment by shaktisingh22** [comment]
Kindly create the Folder and attach the SNAPShOT
![image](https://user-images.githubusercontent.com/83751388/147398510-9fc4010e-27e1-4723-827c-1584fd64d7fc.png)
