### ISSUE TITLE
Not able to fetch output for add functionality in Calculator usercase

### ISSUE THREAD

**Issue by ambikaselenium** [vajrang-b/RPA-Developer-in-30-Days#336]
Env : 

Test data 
NUm 1 = 3
Num 2 = 5

Steps to reproduce
1. execute the calculator use case with above test data
2. Addition functionality

Expected result : Should get the output value 8
Actual result : Getting exception at fetching the result after addition is done

**Comment by vajrang-b** [comment]
@MareesR please take it up
