### ISSUE TITLE
UAT Failed

### ISSUE THREAD

**Issue by vbrroy** [vajrang-b/RPA-Developer-in-30-Days#57]
Calculator UAT failed

**Comment by vajrang-b** [comment]
Can you please give me more specifics and screenshots, logs of the execution

**Comment by Brockxy** [comment]
![Calulator_UAT_Failure](https://user-images.githubusercontent.com/61329341/127427623-08f5045c-cd55-40ed-9131-84dba5150288.JPG)

Logs arent available. Sharing orchestrator screenshot. Kindly look into it.

**Comment by Brockxy** [comment]
@vajrang-b
