### ISSUE TITLE
Testcase

### ISSUE THREAD

**Issue by vajrang-b** [vajrang-b/RPA-Developer-in-30-Days#626]
- [ ] + Operation must be working
- [ ] - operation
- [ ] % operation
- [ ] / operation
- [ ] ++ operation
- [ ] -- Operation

@Datta565 @KiranPhadtare30  @SamuelAnanth  @Udayasree-cloud  @NivyaChinnasamy  @Abhiram1107 

Please test all code executions and if any issue list down in comments

**Comment by Datta565** [comment]
Found compilation error in Division operation.
![Division](https://user-images.githubusercontent.com/127212999/224724061-9b112d90-6527-40df-a6a4-43a262557a49.png)

**Comment by Udayasree-cloud** [comment]
Division Operation is not working correctly.

**Comment by Datta565** [comment]
Are you getting Result 0, Every time?

**Comment by vajrang-b** [comment]
is the testing completed?
