### ISSUE TITLE
Popup Message - Kindly fix

### ISSUE THREAD

**Issue by Brockxy** [vajrang-b/RPA-Developer-in-30-Days#67]
@Ulhasguttikar 

I see a popup message during execution, Couldyou look into it. Attached
![popup](https://user-images.githubusercontent.com/61329341/127591124-f166579f-796e-4429-af67-24242e7aa966.JPG)

**Comment by Ulhasguttikar** [comment]
As per requirement, we need to show the result after performing calculation. so to display the result I have used MessageBox activity and that's why it is showing result in popup message.

**Comment by Brockxy** [comment]
Got it.. Thanks mate

**Comment by vajrang-b** [comment]
as its requirement issue closed
