### ISSUE TITLE
Deploy code

### ISSUE THREAD

**Issue by vajrang-b** [vajrang-b/RPA-Developer-in-30-Days#685]

**Comment by swathinelakurthi** [comment]
Swathi Nelakurthi

**Comment by nav2342** [comment]
@swathinelakurthi 
Code is ready to be deployed, Please deploy it.
[StorageBucket_RF.1.0.2.zip](https://github.com/vajrang-b/RPA-Developer-in-30-Days/files/11918579/StorageBucket_RF.1.0.2.zip)

**Comment by vajrang-b** [comment]
deployment compled
