### ISSUE TITLE
Warnings are not corrected

### ISSUE THREAD

**Issue by paruA32** [vajrang-b/RPA-Developer-in-30-Days#686]
![image](https://github.com/vajrang-b/RPA-Developer-in-30-Days/assets/105871562/0940f418-dc1d-4889-bcbe-832781f968dd)

**Comment by nav2342** [comment]
Assign it to me pls.

**Comment by nav2342** [comment]
![image](https://github.com/vajrang-b/RPA-Developer-in-30-Days/assets/88432106/c6278d1c-9de3-4d56-8dbf-e1563721323b)
@paruA32 
Warnings are corrected and there are no Hub Url's for this project.

**Comment by vajrang-b** [comment]
warnings updated
