### ISSUE TITLE
storage bucket name should not hardcoded in code

### ISSUE THREAD

**Issue by prasuna893** [vajrang-b/RPA-Developer-in-30-Days#687]
![image](https://github.com/vajrang-b/RPA-Developer-in-30-Days/assets/112712529/f1c0c8a3-2210-4700-89ba-5a34ea1ce870)

**Comment by nav2342** [comment]
![image](https://github.com/vajrang-b/RPA-Developer-in-30-Days/assets/88432106/1a47be6b-4ccf-400e-a14f-bd6e008ac8d7)
@prasuna893 
Corrected it, took the Storage Bucket Name from the Config file.

**Comment by vajrang-b** [comment]
validated
