### ISSUE TITLE
Can we display the result after each calculation is Performed?

### ISSUE THREAD

**Issue by Ulhasguttikar** [vajrang-b/RPA-Developer-in-30-Days#71]
@Brockxy 

As per requirement, we need to display the result. Can we make some changes to display result as output after each calculation?

![Roy_Cal Automation](https://user-images.githubusercontent.com/87701644/127607739-e273a243-cedd-440c-89bb-702ed59a65fb.png)

**Comment by Brockxy** [comment]
Yup. I will update.

**Comment by Brockxy** [comment]
Updated and kindly test once you get the latest version 1.0.6

**Comment by Ulhasguttikar** [comment]
issue is resolved
