### ISSUE TITLE
Not clicking CE button after each calculation.

### ISSUE THREAD

**Issue by Ulhasguttikar** [vajrang-b/RPA-Developer-in-30-Days#72]
@Brockxy 

I can see it is clicking CE button at the start of first calculation, but it is not clicking CE before every calculation. 
can we do something to fix that?

**Comment by Brockxy** [comment]
Will check..

**Comment by Brockxy** [comment]
Updated and kindly test once you get the latest version 1.0.6

**Comment by Ulhasguttikar** [comment]
issue resolved
