### ISSUE TITLE
Durvesh Issue regarding Selectors

### ISSUE THREAD

**Issue by Itzsree** [vajrang-b/RPA-Developer-in-30-Days#81]
Close Application 'Windows.UI.Core.CoreWin...': Could not find the UI element corresponding to this selector: [1] <wnd app='applicationframehost.exe' appid='Microsoft.WindowsCalculator_8wekyb3d8bbwe!App' title='Calculator'/> [2] <wnd cls='Windows.UI.Core.CoreWindow' title='Calculator'/> Search failed at selector tag: [1] <wnd app='applicationframehost.exe' appid='Microsoft.WindowsCalculator_8wekyb3d8bbwe!App' title='Calculator'/> The closest matches found are: [37%] <wnd app='applicationframehost.exe' title='Settings'/> [33%] <wnd app='applicationframehost.exe'/>

**Comment by Durveshbendale** [comment]
i have fixed issue please check

**Comment by Itzsree** [comment]
Durvesh code fixed Calculator is working

**Comment by Durveshbendale** [comment]
i have tested @Itzsree  code and it's working fine on my machine.
