### ISSUE TITLE
Folder does not exist

### ISSUE THREAD

**Issue by paruA32** [vajrang-b/RPA-Developer-in-30-Days#843]
![image](https://github.com/vajrang-b/RPA-Developer-in-30-Days/assets/105871562/abcea092-a4c9-4a9b-93e4-64f4fc08e913)
Hi @YashShile , Please check the error related to the folder . In the config file you can can either give the folder name as "shared" or you leave the orchestrator folder name empty

**Comment by YashShile** [comment]
Dear Parvati,

As per your suggestion, I change the folder path to shared. Request you to
move the code in production environment.

Kindly approved the pull request #846.



Thanks and Regards,
Yash Shile

**Comment by paruA32** [comment]
Code moved to production and deployed successfully.

**Comment by YashShile** [comment]
Awesome, thanks for the update!
